# Site configuration

site_name: RetroDECK Wiki
site_description: The Official RetroDECK Wiki

# Copyright
copyright: "&copy; 2023 RetroDECK Team"

# Theme Configuration
theme:
  name: "material"
  language: "en"
  logo: wiki_icons/retrodeck/rd_icon_circle_32x32.png
  features:
    - navigation.prune
  palette:
    scheme: slate
    primary: "deep purple"
    accent: "white"
plugins:
   - search:
   - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
   - blog:
       enabled: true
       post_url_date_format: yyyy/MM/dd
       post_date_format: full
       blog_toc: true
       archive: true
       archive_date_format: yyyy
       pagination: false
       pagination: false
       post_excerpt: required
       post_excerpt_separator: <!-- more -->

# Sidebar Navigation

nav:
  - Wiki Home 🏠: index.md
  - Blog: blog/index.md
  - General Information 📰:
    - What is RetroDECK?: wiki_general/what-is-retrodeck.md
    - What is included in RetroDECK?: wiki_general/what-is-included.md
    - Supported Devices: wiki_general/supported-devices.md
    - The RetroDECK Beta: wiki_general/beta-period.md

  - RetroDECK Configurator 🛠️:
    - Configurator Features: wiki_general/configurator.md

  - FAQ ❔:  wiki_howto_faq/faq.md

  - How-to's 💬:
    - Start using RetroDECK: wiki_howto_faq/retrodeck-start.md
    - Manage your Games: wiki_howto_faq/games-management.md
    - Manage your BIOS/Firmware: wiki_howto_faq/bios-firmware.md
    - Move RetroDECK to a new device: wiki_howto_faq/retrodeck-move.md
    - Add RetroDECK to Steam: wiki_howto_faq/add-to-steam.md
    - Enable Controllers in Steam: wiki_howto_faq/enable-controllers-steam.md
    - Change controller order in Steam: wiki_howto_faq/set-controller-order-steam.md
    - Get the WADs from bought DOOM / DOOM 2 (WIP): wiki_howto_faq/extract-doom-wads.md

  - Steam Deck 🕹️:
    - Steam Deck - RetroDECK Installation and Updates: wiki_devices/steamdeck/steamdeck-start.md
    - Steam Deck - Optimizations: wiki_devices/steamdeck/steamdeck-optimize.md
    - Steam Deck - Recommended Software: wiki_devices/steamdeck/steamdeck-software.md
    - Steam Deck - Controls: wiki_controllers/controllers-steamdeck.md

  - Linux Desktop 🐧:
    - Linux Desktop - Installation and Updates: wiki_devices/linux_desktop/linux-install.md
    - Linux Desktop - Recommended Software: wiki_devices/linux_desktop/linux-software.md

  - EmulationStation-DE Guide 📘:
    - ES-DE User Guide: wiki_emulationStation_de/esde-guide.md
    - ES-DE Themes: wiki_emulationStation_de/esde-themes.md
    - ES-DE Folders and Files (WIP): wiki_emulationStation_de/esde-folders-files.md

  - Emulator Guides 📙:
    - RPCS3: wiki_emulator_guides/rpcs3-guide.md
    - Yuzu: wiki_emulator_guides/yuzu-guide.md
    - ScummVM: wiki_emulator_guides/scummvm-guide.md
    - Cemu (WIP): wiki_emulator_guides/cemu-guide.md
    - Citra (WIP): wiki_emulator_guides/citra-guide.md
    - Dolphin / Primehack (WIP): wiki_emulator_guides/dolphin-primehack-guide.md
    - Duckstation (WIP): wiki_emulator_guides/duckstation-guide.md
    - GZDoom (WIP): wiki_emulator_guides/gzdoom-guide.md
    - IkemenGO - M.U.G.E.N (WIP): wiki_emulator_guides/ikemengo-guide.md
    - MAME (WIP): wiki_emulator_guides/mame-guide.md
    - MelonDS (WIP): wiki_emulator_guides/melonds-guide.md
    - OpenBOR (WIP): wiki_emulator_guides/openbor-guide.md
    - PCSX2 (WIP): wiki_emulator_guides/pcsx2-guide.md
    - PICO-8 (WIP): wiki_emulator_guides/pico8-guide.md
    - PPSSPP (WIP): wiki_emulator_guides/ppsspp-guide.md
    - RetroArch (WIP): wiki_emulator_guides/retroarch-guide.md
    - Ryujinx (WIP): wiki_emulator_guides/ryujinx-guide.md
    - Solarus (WIP): wiki_emulator_guides/solarus-guide.md
    - Vita3K: wiki_emulator_guides/vita3k-guide.md
    - Xemu (WIP): wiki_emulator_guides/xemu-guide.md

  - Mod Guides ⚙️:
    - Mods - Citra: wiki_mods/citra-mods.md
    - Mods - Dolphin/Primehack: wiki_mods/dolphin-prime-mods.md
    - Mods - Ryujinx (WIP): wiki_mods/ryujinx-mods.md
    - Mods - Yuzu: wiki_mods/yuzu-mods.md

  - Texture Pack Guides 🖌️:
    - Texture Packs - Citra: wiki_texture_packs/citra-tp.md
    - Texture Packs - Dolphin/Primehack: wiki_texture_packs/dolphing-prime-tp.md
    - Texture Packs - Duckstation: wiki_texture_packs/duckstation-tp.md
    - Texture Packs - PCSX2: wiki_texture_packs/pcsx2-tp.md
    - Texture Packs - PPSSPP: wiki_texture_packs/ppsspp-tp.md
    - Texture Packs - RetroArch Mesen: wiki_texture_packs/retroarch-mesen-tp.md
    - Texture Packs - RetroArch Mupen64Plus: wiki_texture_packs/retroarch-mupen64plus-tp.md

  - Controllers & Input 🎮:
    - Different Button Prompts in Games: wiki_controllers/diffrent-game-inputs.md
    - RetroDECK with Steam Input: wiki_controllers/about-steam-input.md
    - RetroDECK and Udev Rules: wiki_controllers/about-udev.md
    - Accessibility - Controllers (WIP): wiki_controllers/controllers-accessibility.md
    - Arcade - Controllers (WIP): wiki_controllers/controllers-arcade.md
    - Flight - Controllers (WIP): wiki_controllers/controllers-flight.md
    - Generic - Controllers (WIP): wiki_controllers/controllers-generic.md
    - Gimmick - Controllers (WIP): wiki_controllers/controllers-gimmick.md
    - Lightguns - Controllers (WIP): wiki_controllers/controllers-lightguns.md
    - Motion - Controllers (WIP): wiki_controllers/controllers-motion.md
    - Music / Rhythm - Controllers (WIP): wiki_controllers/controllers-music.md
    - Nintendo - Controllers (WIP): wiki_controllers/controllers-nintendo.md
    - Playstation - Controllers (WIP): wiki_controllers/controllers-playstation.md
    - Racing - Controllers (WIP): wiki_controllers/controllers-racing.md
    - Steam Deck - Controller: wiki_controllers/controllers-steamdeck.md
    - Valve - Steam Controller (WIP): wiki_controllers/controllers-steam.md
    - Toys-to-life - Controllers (WIP): wiki_controllers/controllers-toys-to-life.md
    - Xbox - Controllers (WIP): wiki_controllers/controllers-xbox.md

  - Community & Helping Out ❤️:
    - Discord: wiki_community/discord.md
    - Lemmy/Reddit: wiki_community/lemmy-reddit.md
    - How to Contribute to RetroDECK?: wiki_community/contibute-rd.md
    - How to help out with testing?: wiki_community/testing-rd.md

  - Bugs & Issues 🐜:
    - Reporting: wiki_bugs/report-bugs.md
    - Known Issues: wiki_bugs/known-issues.md

  - Donations & Licenses 🎁: wiki_about/donations-licenses.md

  - Development 🖥️:
    - Current Version: wiki_rd_versions/version_0.7b/0.7.5b.md
    - Version History (Patchnotes): wiki_rd_versions/version-history.md
    - What are you working on?: wiki_development/what-are-you-working.on.md
    - Folders and Filepaths: wiki_development/folders-filepaths.md
    - CLI Guide: wiki_development/cli-guide.md
    - Development Notes: wiki_development/general-development.md

  - About RetroDECK 📖:
    - The Team & Credits: wiki_about/team-credits.md
    - Story & Philosophy: wiki_about/story-philosophy.md
    - Visions & Goals: wiki_about/visions-and-goals.md
    - Boot Logos: wiki_about/boot-logos.md
